spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: ${AUTH_ADM_DB:admin}
      username: ${USERNAME:root}
      password: ${PASSWORD:example}
      database: ${DB_APP:hexagonal}

study:
  client:
    address:
      url: ${URL_ADDRESS:http://localhost:8082/addresses}